/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'surface': '#fcf8fd',
        'surface-dim': '#dcd9de',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f2f7',
        'surface-container': '#f1ecf2',
        'surface-container-high': '#ebe7ec',
        'surface-container-highest': '#e5e1e6',
        'on-surface': '#1c1b1f',
        'on-surface-variant': '#47464f',
        'outline': '#787680',
        'outline-variant': '#c8c5d0',
        'surface-tint': '#5b598c',
        'primary': '#070235',
        'on-primary': '#ffffff',
        'primary-container': '#1e1b4b',
        'on-primary-container': '#8683ba',
        'inverse-primary': '#c4c1fb',
        'secondary': '#5c5f60',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1e3e4',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'background': '#fcf8fd',
        'on-background': '#1c1b1f',
        'surface-variant': '#e5e1e6',
        'accent': '#818CF8',
        'primary-fixed': '#e3dfff',
        'primary-fixed-dim': '#c4c1fb',
        'on-primary-fixed': '#181445',
        'on-primary-fixed-variant': '#444173',
        'inverse-surface': '#313034',
        'inverse-on-surface': '#f3eff4',
        'tertiary': '#160700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#371a00',
        'on-tertiary-container': '#ae7f59',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
